version: '3.9'

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    env_file: .env
    volumes:
      - static:/api/static
      - media:/api/media
    ports:
      - "8000:8000"
    depends_on:
      - db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    command: ["redis-server"]
    depends_on:
      - backend
      - db

  db:
    image: postgres:latest
    container_name: db
    env_file: .env
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery
    entrypoint: ['celery', '-A', 'api', 'worker', '-l', 'info', '-P', 'eventlet']
    restart: always
    env_file: .env
    volumes:
      - static:/api/static
      - media:/api/media
    environment:
      C_FORCE_ROOT: "false"
      CELERY_BROKER_URL: 'redis://redis:6379/0'
      CELERY_RESULT_BACKEND: 'redis://redis:6379/0'
    depends_on:
      - backend
      - db
      - redis

volumes:
  postgres_data:
  static:
  media: