# Generated by Django 4.2.6 on 2023-10-07 09:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import image_api.utils
import re
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(default='Basic', max_length=150, unique=True)),
                ('thumbnail_sizes', models.CharField(blank=True, default=None, max_length=150, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('original_link', models.BooleanField(default=False)),
                ('expiration_link', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'account_tier',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('image', models.ImageField(height_field='height', upload_to=image_api.utils.user_directory_path, width_field='width')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('thumbnail_sizes', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='image_api.image')),
            ],
            options={
                'db_table': 'image',
            },
        ),
        migrations.CreateModel(
            name='ExpirationLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_api.image')),
            ],
            options={
                'db_table': 'expiration_link',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='image_api.accounttier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
