# Generated by Django 4.2.6 on 2023-10-07 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='thumbnail_sizes',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='image_api.image'),
        ),
    ]
