# Generated by Django 4.2.6 on 2023-10-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_api', '0002_alter_image_thumbnail_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='original_photo',
            field=models.BooleanField(default=False),
        ),
    ]
